### ISSUE TITLE
How to get Vercel like logs?

### ISSUE THREAD

**Issue by bitttttten** [sainsburys-tech/next-logger#61]
In Vercel, you are able to see access logs and request logs, just like:

![image](https://github.com/user-attachments/assets/02ca7b1d-b055-4377-bc09-312ce0fc78e1)

I appreciate this library, formatting all the console.logs for us however Next.JS is very quiet by default. i.e.

```sh
$ docker run -p 3000:3000 nextjs
  ▲ Next.js 14.2.3
  - Local:        http://822e01df4cab:3000
  - Network:      http://172.17.0.2:3000

 ✓ Starting...
{"level":30,"time":1723899099678,"pid":1,"hostname":"822e01df4cab","name":"console","msg":" ✓ Ready in 236ms"}
```

Even after we visit 100+ pages, we don't see any additional logs like response status, user agent, etc.
I don't think this is this libraries aim, although, could it be something added to this library too? 

If there are other libraries solving this problem, please let me know too 🙏

**Comment by atkinchris** [comment]
This library solely focuses on how to expose your existing logging in JSON format - rather than setting opinions on log levels or verbosity, or providing extra logging instrumentation.

What you're seeing here in that screenshot are HTTP traffic logs, akin to those you'd get out of nginx on its noisier settings. Next.js doesn't have a setting to enable these from its server by default. There's a discussion about this here: https://github.com/vercel/next.js/discussions/22945#discussioncomment-3361021, along with workarounds using middleware.
